export const WORKOUT_TYPES = [
  "Weightlifting",
  "Running",
  "Pilates",
  "Swimming",
  "Barre",
  "Basketball",
  "Bodyweight Training",
  "Bootcamp",
  "Boxing",
  "Brazilian Jiu-Jitsu",
  "Circuit Training",
  "CrossFit",
  "Cycling",
  "Dancing",
  "HIIT",
  "Kettlebell Training",
  "Kickboxing",
  "Mobility Flow",
  "Muay Thai",
  "Pickleball",
  "Powerlifting",
  "Qigong",
  "Resistance Band Training",
  "Rock Climbing",
  "Rowing",
  "Soccer",
  "Spartan",
  "Stair Climbing",
  "Stretching",
  "Strongman",
  "Tabata",
  "Tai Chi",
  "Tennis",
  "Walking",
  "Yoga"
];
